### PR TITLE
Add a new method add_host_with_statements

### PR DESCRIPTION
**Pull request by sagarun**
We want to set hostname, routers and domain in the dhcp lease file.
The method add_host_with_statements accepts router,domain and hostname
and sets those statements using omapi in the lease file. The method
also handles case when any of the statements are missing.

### CODE REVIEW

**Comment by cygnusb** [comment]
Thanks for your contribution. Please provide a pull request without the version bump. Thanks!

**Comment by sagarun** [comment]
@cygnusb  Done. Thanks.

**Comment by sagarun** [comment]
@cygnusb  Done. Thanks.

**Comment by sagarun** [comment]
@cygnusb I did revert the version bump. Do you see it?  If you'd like to merge this as a single commit, you can 'squash merge' it. If not i can make this into  a single commit.  Let me know.

**Comment by sagarun** [comment]
@cygnusb Just made it into a one clean commit now. Removed the version stuff.

**Comment by cygnusb** [comment]
Please change the function parameters to not be kwargs. For the optional parameters you can use None as default value.

**Comment by sagarun** [comment]
@cygnusb Yes. I have removed the kwargs.

**Comment by cygnusb** [comment]
Please add documentation for all parameters. See other functions as reference

**Comment by cygnusb** [comment]
And please reorder parameters, to be in sync with def add_host_supersede_name. 
Wouldn't it be better to name this function add_host_supersede and have multiple optional parameters be present?

**Comment by sagarun** [comment]
@cygnusb reordered the parameters, renamed the method to add_host_supersede, added doctrings about the parameter types. Thanks for talking time to review. Let me know if you want me to change anything else.

**Comment by cygnusb** [comment]
The check for name, ip and mac is now obsolete and can be removed. In addition also the "if ip" statement below can be removed.
Afterwards I think this can be merged. Thanks!

**Comment by sagarun** [comment]
@cygnusb  Done. Thanks.

**Comment by cygnusb** [comment]
Thank you!

**Comment by sagarun** [comment]
@cygnusb Any chance it will get pushed to pypi? I still see 0.6 in pypi, can you make a release please?

**Pull request merged**
