### PR TITLE
pep8 fixes and some new host config methods

### PR DESCRIPTION
**Pull request by shraddha-pandhe**
This commit fixes some pep8 issues

@cygnusb , @neirbowj, can you please review it? Please let me know if you have any questions.

### CODE REVIEW

**Comment by neirbowj** [comment]
Please decompose this into a set of commits that can be individually reviewed. In particular, whitespace-only changes should be in a separate commit. If you espouse OpenStack, see [that project's guidance](https://wiki.openstack.org/wiki/GitCommitMessages#Structural_split_of_changes) for more details.

Disclaimer: I am merely an interested party, but have no authority over this project. I defer to the primary author on questions of style and standards.

**Comment by shraddha-pandhe** [comment]
@neirbowj, thanks for the review. I will use separate commits to address the changes.

**Comment by shraddha-pandhe** [comment]
Hi @neirbowj, I have updated the pull request according to the comments. Please take a look.

**Comment by cygnusb** [comment]
Sorry, but I will not accept these changes.
We use tabs instead of spaces. This consistent with PEP8, which states that "Tabs should be used solely to remain consistent with code that is already indented with tabs."
You also change the interpreter to /usr/bin/python, which will not work on other systems. /usr/bin/env python is much better than /usr/bin/python.
Your code also breaks the current api.

**Comment by cygnusb** [comment]
My suggestion is you provide additional wrapper methods, which will call the existing methods. In this way the api will not be broken. And please also stick to indenting by tabs.
Please provide minimal changeset in different commits, so that we can accept single changes

**Comment by shraddha-pandhe** [comment]
Hi @cygnusb, can you please explain me how my change breaks the API?

**Comment by cygnusb** [comment]
You have renamed existing functions, that other people might use in their software. So renaming of public functions is in general a bad idea, since this might brake software, which is using pypureomapi.
You might add additional function with a new name, which are calling the existing functions. This leaves the api intact. For example:
'''
def lookup_ip_by_mac(self, mac):
  return lookup_ip(mac)
'''
I cannot see any reason, why one would need this renamed functions. Can you please explain, why you think these are necessary?

**Comment by shraddha-pandhe** [comment]
That makes sense. I can write wrapper methods.

The reason why I want to rename is because,  based on name 'lookup_ip', I don't really understand whether I am supplying IP as argument or trying to find out the IP. Also, I don't know whether my query argument is mac or name - both can be used to search a host record.

**Comment by shraddha-pandhe** [comment]
@cygnusb, would you prefer if I open Issues first and then submit pull requests once the Issues are confirmed?

**Comment by cygnusb** [comment]
The function documentation should clarify this. So do not see any reason why to introduce duplicate functions providing the same functionality

**Comment by shraddha-pandhe** [comment]
@cygnusb, thats correct, the function documentation should clarify this. But this documentations is helpful when someone is actually writing code that uses this API. I am thinking more from the point of view of someone who is reading the code that calls this API. For someone who is reviewing that code, its not clear what exactly
     def lookup_ip()

does. It the reviewer would have to open this library code in order to find out whether its used correctly or not. If the method names are descriptive enough, that wont be necessary.

**Comment by cygnusb** [comment]
I don't see any problems there and a duplication of the interaface creates more unclear code. So I am closing this pull request.

**Comment by shraddha-pandhe** [comment]
@cygnusb , there are more changes than pep8 and method renames. I have added some methods to create host object. Would you like to discuss those?

**Comment by cygnusb** [comment]
Sure. Please provide a seperate pull request using tabs as indent and containing only the relevant code for review.

**Pull request closed without merging**
